# Generated by Django 3.1.13 on 2021-08-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='coordinator1',
            field=models.CharField(choices=[], default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='coordinator2',
            field=models.CharField(choices=[], default='A', max_length=10),
        ),
    ]
