# Generated by Django 3.1.13 on 2022-01-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210827_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='coordinator1',
            field=models.CharField(choices=[('onkar', 'onkar'), ('onkar2', 'onkar2')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='coordinator2',
            field=models.CharField(choices=[('onkar', 'onkar'), ('onkar2', 'onkar2')], default='A', max_length=10),
        ),
    ]
