# Generated by Django 3.1.13 on 2022-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Uploaded', 'Uploaded')], default='Queued', max_length=30),
        ),
    ]
