# Generated by Django 3.1.13 on 2022-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220815_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='coordinator1',
            field=models.CharField(choices=[('onkar', 'onkar'), ('onkar232323', 'onkar232323')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='coordinator2',
            field=models.CharField(choices=[('onkar', 'onkar'), ('onkar232323', 'onkar232323')], default='A', max_length=20),
        ),
    ]
