# Generated by Django 3.1.13 on 2022-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220815_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='coordinator1',
            field=models.CharField(choices=[('onkar', 'onkar'), ('onkar2', 'onkar2'), ('onka123', 'onka123')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='coordinator2',
            field=models.CharField(choices=[('onkar', 'onkar'), ('onkar2', 'onkar2'), ('onka123', 'onka123')], default='A', max_length=20),
        ),
    ]
