# Generated by Django 3.1.13 on 2022-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220815_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='coordinator1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='coordinator2',
            field=models.CharField(max_length=20),
        ),
    ]
